INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Big Boi - Boomiverse', 'Big Boi', 'Boomiverse', '10. Made Man (Ft. Killer Mike _ Kurupt).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Anderson .Paak - Malibu', 'Anderson .Paak', 'Malibu', '13. Come Down.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'A$AP Ferg - Still Striving (2017)', 'A$AP Ferg', 'Still Striving (2017)', '08 Plain Jane.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'A Tribe Called Quest - We Got It From Here... Thank You 4 Your Service', 'A Tribe Called Quest', 'We Got It From Here... Thank You 4 Your Service', '09. Mobius.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( '_sc1', 'unknown', 'unknown', '01. Look Out For Detox.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( '_sc1', 'unknown', 'unknown', 'Mask Off RMX_3071836_audiomack.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( '21 Savage, Offset & Metro Boomin - Without Warning (2017)', '21 Savage, Offset & Metro Boomin', 'Without Warning (2017)', '03 Ric Flair Drip.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Binary Star - Masters Of The Universe', 'Binary Star', 'Masters Of The Universe', '18 Glen Close.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'The Pharcyde - Bizarre Ride II the Pharcyde', 'The Pharcyde', 'Bizarre Ride II the Pharcyde', '12 - Pharcyde - Passing Me By.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Black Milk - Glitches in the Break (2014)', 'Black Milk', 'Glitches in the Break (2014)', '02 - Dirt Bells.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Black Milk - If Theres A Hell Below 320', 'Black Milk', 'If Theres A Hell Below 320', 'Black Milk - If Theres A Hell Below - 07 Story and Her.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Black Milk-No_Poison_No_Paradise-2013-C4', 'unknown', 'unknown', '10-black_milk-parallels_(feat_ab).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Bone thugs-n-harmony  - E. 1999 Eternal', 'Bone thugs-n-harmony ', 'E. 1999 Eternal', '08 Tha Crossroads.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'J. Cole - Born Sinner (Deluxe Edition) [320]_CD1', 'J. Cole', 'Born Sinner (Deluxe Edition) [320]_CD1', '07 - Runaway.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'J. Cole - Born Sinner (Deluxe Edition) [320]_CD1', 'J. Cole', 'Born Sinner (Deluxe Edition) [320]_CD1', '04 - Power Trip (Feat. Miguel).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Denzel Curry - ZUU', 'Denzel Curry', 'ZUU', '5 - AUTOMATIC.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Denzel Curry - ZUU', 'Denzel Curry', 'ZUU', '4 - BIRDZ.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Freddie Gibbs & Madlib - Bandana', 'Freddie Gibbs & Madlib', 'Bandana', '10. Freddie Gibbs & Madlib - Giannis (feat. Anderson .Paak).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Flatbush Zombies - Better Off Dead', 'Flatbush Zombies', 'Better Off Dead', '02 Nephilim [prod. Erick Arc Elliott].mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Wu-Tang Clan - Enter The Wu-Tang 36 Chambers', 'Wu-Tang Clan', 'Enter The Wu-Tang 36 Chambers', '12 - Wu-Tang Clan - Wu-Tang- 7th Chamber - Part II.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'DUCKWRTH - The Falling Man', 'DUCKWRTH', 'The Falling Man', '04. NOBODY FALLS feat. Kiana Ledé, Terrace Martin & Medasin.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'DUCKWRTH - The Falling Man', 'DUCKWRTH', 'The Falling Man', '06. SOPRANO.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Young Thug - No, My Name is Jeffery', 'Young Thug', 'No, My Name is Jeffery', '07. Harambe.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'YBN Cordae - The Lost Boy', 'YBN Cordae', 'The Lost Boy', '04. Bad Idea (feat. Chance the Rapper).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Vince Staples - Hell Can Wait (2014) 320', 'Vince Staples', 'Hell Can Wait (2014) 320', '01 - Fire.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Vince Staples - Hell Can Wait (2014) 320', 'Vince Staples', 'Hell Can Wait (2014) 320', '02 - 65 Hunnid.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Travis Scott - ASTROWORLD (FLAC)', 'Travis Scott', 'ASTROWORLD (FLAC)', '01. STARGAZING.flac' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Travis Scott - ASTROWORLD (FLAC)', 'Travis Scott', 'ASTROWORLD (FLAC)', '12. YOSEMITE feat. NAV.flac' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Travis Scott - ASTROWORLD (FLAC)', 'Travis Scott', 'ASTROWORLD (FLAC)', '15. BUTTERFLY EFFECT.flac' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'The_Notorious_B.I.G.-Greatest_Hits-(Proper)-2007-EON', 'unknown', 'unknown', '01-the_notorious_b.i.g.-juicy.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'The_Notorious_B.I.G.-Greatest_Hits-(Proper)-2007-EON', 'unknown', 'unknown', '10-the_notorious_b.i.g.-notorious_thugs_(ft._bone_thugs_and_harmony).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Smino - Blkswn', 'Smino', 'Blkswn', '18. Amphetamine.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Smino - Blkswn', 'Smino', 'Blkswn', '12. Blkoscars (Ft. Jay2).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'SiR - November', 'SiR', 'November', '04. DEvils.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Rich The Kid - The World Is Yours', 'Rich The Kid', 'The World Is Yours', '04. Plug Walk.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Rico Nasty & Kenny Beats - Anger Management', 'Rico Nasty & Kenny Beats', 'Anger Management', '03. Hatin.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Pusha_T-My_Name_Is_My_Name-2013-WHOA', 'unknown', 'unknown', '02-pusha_t-numbers_on_the_board-whoa.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Pro_Era-Joey_BADA-1999', 'unknown', 'unknown', '11-Joey_Bada-Snakes_Feat_T_nah_Apex_Prod_By_J_Dilla.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Big Boi - Boomiverse', 'Big Boi', 'Boomiverse', '10. Made Man (Ft. Killer Mike _ Kurupt).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Anderson .Paak - Malibu', 'Anderson .Paak', 'Malibu', '13. Come Down.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'A$AP Ferg - Still Striving (2017)', 'A$AP Ferg', 'Still Striving (2017)', '08 Plain Jane.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'A Tribe Called Quest - We Got It From Here... Thank You 4 Your Service', 'A Tribe Called Quest', 'We Got It From Here... Thank You 4 Your Service', '09. Mobius.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( '_sc1', 'unknown', 'unknown', '01. Look Out For Detox.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( '_sc1', 'unknown', 'unknown', 'Mask Off RMX_3071836_audiomack.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( '21 Savage, Offset & Metro Boomin - Without Warning (2017)', '21 Savage, Offset & Metro Boomin', 'Without Warning (2017)', '03 Ric Flair Drip.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Binary Star - Masters Of The Universe', 'Binary Star', 'Masters Of The Universe', '18 Glen Close.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'The Pharcyde - Bizarre Ride II the Pharcyde', 'The Pharcyde', 'Bizarre Ride II the Pharcyde', '12 - Pharcyde - Passing Me By.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Black Milk - Glitches in the Break (2014)', 'Black Milk', 'Glitches in the Break (2014)', '02 - Dirt Bells.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Black Milk - If Theres A Hell Below 320', 'Black Milk', 'If Theres A Hell Below 320', 'Black Milk - If Theres A Hell Below - 07 Story and Her.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Black Milk-No_Poison_No_Paradise-2013-C4', 'unknown', 'unknown', '10-black_milk-parallels_(feat_ab).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Bone thugs-n-harmony  - E. 1999 Eternal', 'Bone thugs-n-harmony ', 'E. 1999 Eternal', '08 Tha Crossroads.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'J. Cole - Born Sinner (Deluxe Edition) [320]_CD1', 'J. Cole', 'Born Sinner (Deluxe Edition) [320]_CD1', '07 - Runaway.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'J. Cole - Born Sinner (Deluxe Edition) [320]_CD1', 'J. Cole', 'Born Sinner (Deluxe Edition) [320]_CD1', '04 - Power Trip (Feat. Miguel).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Denzel Curry - ZUU', 'Denzel Curry', 'ZUU', '5 - AUTOMATIC.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Denzel Curry - ZUU', 'Denzel Curry', 'ZUU', '4 - BIRDZ.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Freddie Gibbs & Madlib - Bandana', 'Freddie Gibbs & Madlib', 'Bandana', '10. Freddie Gibbs & Madlib - Giannis (feat. Anderson .Paak).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Flatbush Zombies - Better Off Dead', 'Flatbush Zombies', 'Better Off Dead', '02 Nephilim [prod. Erick Arc Elliott].mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Wu-Tang Clan - Enter The Wu-Tang 36 Chambers', 'Wu-Tang Clan', 'Enter The Wu-Tang 36 Chambers', '12 - Wu-Tang Clan - Wu-Tang- 7th Chamber - Part II.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'DUCKWRTH - The Falling Man', 'DUCKWRTH', 'The Falling Man', '04. NOBODY FALLS feat. Kiana Ledé, Terrace Martin & Medasin.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'DUCKWRTH - The Falling Man', 'DUCKWRTH', 'The Falling Man', '06. SOPRANO.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Young Thug - No, My Name is Jeffery', 'Young Thug', 'No, My Name is Jeffery', '07. Harambe.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'YBN Cordae - The Lost Boy', 'YBN Cordae', 'The Lost Boy', '04. Bad Idea (feat. Chance the Rapper).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Vince Staples - Hell Can Wait (2014) 320', 'Vince Staples', 'Hell Can Wait (2014) 320', '01 - Fire.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Vince Staples - Hell Can Wait (2014) 320', 'Vince Staples', 'Hell Can Wait (2014) 320', '02 - 65 Hunnid.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Travis Scott - ASTROWORLD (FLAC)', 'Travis Scott', 'ASTROWORLD (FLAC)', '01. STARGAZING.flac' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Travis Scott - ASTROWORLD (FLAC)', 'Travis Scott', 'ASTROWORLD (FLAC)', '12. YOSEMITE feat. NAV.flac' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Travis Scott - ASTROWORLD (FLAC)', 'Travis Scott', 'ASTROWORLD (FLAC)', '15. BUTTERFLY EFFECT.flac' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'The_Notorious_B.I.G.-Greatest_Hits-(Proper)-2007-EON', 'unknown', 'unknown', '01-the_notorious_b.i.g.-juicy.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'The_Notorious_B.I.G.-Greatest_Hits-(Proper)-2007-EON', 'unknown', 'unknown', '10-the_notorious_b.i.g.-notorious_thugs_(ft._bone_thugs_and_harmony).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Smino - Blkswn', 'Smino', 'Blkswn', '18. Amphetamine.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Smino - Blkswn', 'Smino', 'Blkswn', '12. Blkoscars (Ft. Jay2).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'SiR - November', 'SiR', 'November', '04. DEvils.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Rich The Kid - The World Is Yours', 'Rich The Kid', 'The World Is Yours', '04. Plug Walk.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Rico Nasty & Kenny Beats - Anger Management', 'Rico Nasty & Kenny Beats', 'Anger Management', '03. Hatin.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Pusha_T-My_Name_Is_My_Name-2013-WHOA', 'unknown', 'unknown', '02-pusha_t-numbers_on_the_board-whoa.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Pro_Era-Joey_BADA-1999', 'unknown', 'unknown', '11-Joey_Bada-Snakes_Feat_T_nah_Apex_Prod_By_J_Dilla.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'pro era - PEEP The aPROcalypse final', 'pro era', 'PEEP The aPROcalypse final', '01 Like Water  - Capital STEEZ, Joey Bada$$ & Cj Fly (Produced by Statik Selektah).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'outkast - Southernplayalisticadillacmuzik (1994)', 'outkast', 'Southernplayalisticadillacmuzik (1994)', 'Southernplayalisticadillacmuzik - 02 - Myintrotoletuknow.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'maxo kream - Brandon Banks', 'maxo kream', 'Brandon Banks', '05 8 Figures.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Madvillain - Madvillainy [V0]', 'Madvillain', 'Madvillainy [V0]', '21 - Madvillain - Great Day.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'KOD', 'unknown', 'unknown', '05. J. Cole - ATM.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - Untitled Mastered', 'Kendrick Lamar', 'Untitled Mastered', '02. Untitled 02 (06.23.2014).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - Untitled Mastered', 'Kendrick Lamar', 'Untitled Mastered', '05. Untitled 05 (09.21.2014).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - Untitled Mastered', 'Kendrick Lamar', 'Untitled Mastered', '07. Untitled 07 (2014 - 2016).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - Untitled Mastered', 'Kendrick Lamar', 'Untitled Mastered', '08. Untitled 08 (09.06.2014).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - DAMN', 'Kendrick Lamar', 'DAMN', '05. FEEL..mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - DAMN', 'Kendrick Lamar', 'DAMN', '12. FEAR..mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - Bad Kid Chill City (EP) (2018) (320kbps)', 'Kendrick Lamar', 'Bad Kid Chill City (EP) (2018) (320kbps)', '06. Kendrick Lamar - Heroin (Feat. SZA, Jay Rock, Isaiah Rashad & Ab-Soul).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kanye West - Ye', 'Kanye West', 'Ye', '07. Violent Crimes feat. DeJ Loaf, Nicki Minaj & Willow Smith.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kanye West - Yandhi (2018) [mp3 V0]', 'Kanye West', 'Yandhi (2018) [mp3 V0]', '10. Denzel Interlude.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'J.I.D - The Never Story', 'J.I.D', 'The Never Story', '07. All Bad (Ft. Mereba).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'J.I.D - DiCaprio 2', 'J.I.D', 'DiCaprio 2', '06. Off Da Zoinkys.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'G.O.O.D. Music - Cruel Summer V0-2012', 'G.O.O.D. Music', 'Cruel Summer V0-2012', '04 New God Flow.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EarthGang - Rags EP', 'EarthGang', 'Rags EP', '01. Mediate.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EarthGang - Rags EP', 'EarthGang', 'Rags EP', '03. Red Light.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Future - Future', 'Future', 'Future', '17. Feds Did a Sweep.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'New folder', 'unknown', 'unknown', 'THat Part (Black Hippy REMIX).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kanye West, Gucci Mane, Big Sean, 2 Chainz, Travis_Champions [Explicit]', 'unknown', 'unknown', '01 - Champions [Explicit].mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '01. Cocktail.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '02. Skit 1.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '03. Build.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '04. Nothing but the Best feat. Ari Lennox.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '05. Skit 2.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '06. Off the Lot feat. Mereba.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '07. LOLSMH.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '08. Skit 3.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Earthgang - Robots (2017)', 'Earthgang', 'Robots (2017)', '01 - Lyfted Intro.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Earthgang - Robots (2017)', 'Earthgang', 'Robots (2017)', '02 - Artificial.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Earthgang - Robots (2017)', 'Earthgang', 'Robots (2017)', '03 - Robots.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Earthgang - Robots (2017)', 'Earthgang', 'Robots (2017)', '04 - Underwater (feat. Sir).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Earthgang - Robots (2017)', 'Earthgang', 'Robots (2017)', '05 - So Many Feelings.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Earthgang - Robots (2017)', 'Earthgang', 'Robots (2017)', '06 - Flickted.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'New folder', 'unknown', 'unknown', 'Glorious Thugs.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'ASAP Ferg - Floor Seats', 'ASAP Ferg', 'Floor Seats', 'A$AP Ferg - Floor Seats.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'ASAP Ferg - Floor Seats', 'ASAP Ferg', 'Floor Seats', 'A$AP Ferg - Jet Lag.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'ASAP Ferg - Floor Seats', 'ASAP Ferg', 'Floor Seats', 'A$AP Ferg - WAM.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'ASAP Ferg - Floor Seats', 'ASAP Ferg', 'Floor Seats', 'A$AP Ferg - Ride.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Domo Genesis - Genesis', 'Domo Genesis', 'Genesis', '07. Coming Back (Ft. Mac Miller).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Maxo Kream - Punken', 'Maxo Kream', 'Punken', '08. Astrodome, Pt. 2.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Maxo Kream - Punken', 'Maxo Kream', 'Punken', '10. Pop Another.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Maxo Kream - Punken', 'Maxo Kream', 'Punken', '05. Hobbies.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Little Simz - GREY Area (2019)', 'Little Simz', 'GREY Area (2019)', '08. Therapy.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'New folder', 'unknown', 'unknown', 'Ab-Soul - W.W.S.D..mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'New folder', 'unknown', 'unknown', 'Jay Electronica - better in tune w the infinite ft. LaTonya Givens.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Big Boi - Boomiverse', 'Big Boi', 'Boomiverse', '10. Made Man (Ft. Killer Mike _ Kurupt).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Anderson .Paak - Malibu', 'Anderson .Paak', 'Malibu', '13. Come Down.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'A$AP Ferg - Still Striving (2017)', 'A$AP Ferg', 'Still Striving (2017)', '08 Plain Jane.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'A Tribe Called Quest - We Got It From Here... Thank You 4 Your Service', 'A Tribe Called Quest', 'We Got It From Here... Thank You 4 Your Service', '09. Mobius.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( '_sc1', 'unknown', 'unknown', '01. Look Out For Detox.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( '_sc1', 'unknown', 'unknown', 'Mask Off RMX_3071836_audiomack.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( '21 Savage, Offset & Metro Boomin - Without Warning (2017)', '21 Savage, Offset & Metro Boomin', 'Without Warning (2017)', '03 Ric Flair Drip.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Binary Star - Masters Of The Universe', 'Binary Star', 'Masters Of The Universe', '18 Glen Close.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'The Pharcyde - Bizarre Ride II the Pharcyde', 'The Pharcyde', 'Bizarre Ride II the Pharcyde', '12 - Pharcyde - Passing Me By.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Black Milk - Glitches in the Break (2014)', 'Black Milk', 'Glitches in the Break (2014)', '02 - Dirt Bells.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Black Milk - If Theres A Hell Below 320', 'Black Milk', 'If Theres A Hell Below 320', 'Black Milk - If Theres A Hell Below - 07 Story and Her.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Black Milk-No_Poison_No_Paradise-2013-C4', 'unknown', 'unknown', '10-black_milk-parallels_(feat_ab).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Bone thugs-n-harmony  - E. 1999 Eternal', 'Bone thugs-n-harmony ', 'E. 1999 Eternal', '08 Tha Crossroads.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'J. Cole - Born Sinner (Deluxe Edition) [320]_CD1', 'J. Cole', 'Born Sinner (Deluxe Edition) [320]_CD1', '07 - Runaway.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'J. Cole - Born Sinner (Deluxe Edition) [320]_CD1', 'J. Cole', 'Born Sinner (Deluxe Edition) [320]_CD1', '04 - Power Trip (Feat. Miguel).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Denzel Curry - ZUU', 'Denzel Curry', 'ZUU', '5 - AUTOMATIC.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Denzel Curry - ZUU', 'Denzel Curry', 'ZUU', '4 - BIRDZ.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Freddie Gibbs & Madlib - Bandana', 'Freddie Gibbs & Madlib', 'Bandana', '10. Freddie Gibbs & Madlib - Giannis (feat. Anderson .Paak).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Flatbush Zombies - Better Off Dead', 'Flatbush Zombies', 'Better Off Dead', '02 Nephilim [prod. Erick Arc Elliott].mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Wu-Tang Clan - Enter The Wu-Tang 36 Chambers', 'Wu-Tang Clan', 'Enter The Wu-Tang 36 Chambers', '12 - Wu-Tang Clan - Wu-Tang- 7th Chamber - Part II.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'DUCKWRTH - The Falling Man', 'DUCKWRTH', 'The Falling Man', '04. NOBODY FALLS feat. Kiana Ledé, Terrace Martin & Medasin.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'DUCKWRTH - The Falling Man', 'DUCKWRTH', 'The Falling Man', '06. SOPRANO.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Young Thug - No, My Name is Jeffery', 'Young Thug', 'No, My Name is Jeffery', '07. Harambe.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'YBN Cordae - The Lost Boy', 'YBN Cordae', 'The Lost Boy', '04. Bad Idea (feat. Chance the Rapper).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Vince Staples - Hell Can Wait (2014) 320', 'Vince Staples', 'Hell Can Wait (2014) 320', '01 - Fire.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Vince Staples - Hell Can Wait (2014) 320', 'Vince Staples', 'Hell Can Wait (2014) 320', '02 - 65 Hunnid.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Travis Scott - ASTROWORLD (FLAC)', 'Travis Scott', 'ASTROWORLD (FLAC)', '01. STARGAZING.flac' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Travis Scott - ASTROWORLD (FLAC)', 'Travis Scott', 'ASTROWORLD (FLAC)', '12. YOSEMITE feat. NAV.flac' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Travis Scott - ASTROWORLD (FLAC)', 'Travis Scott', 'ASTROWORLD (FLAC)', '15. BUTTERFLY EFFECT.flac' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'The_Notorious_B.I.G.-Greatest_Hits-(Proper)-2007-EON', 'unknown', 'unknown', '01-the_notorious_b.i.g.-juicy.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'The_Notorious_B.I.G.-Greatest_Hits-(Proper)-2007-EON', 'unknown', 'unknown', '10-the_notorious_b.i.g.-notorious_thugs_(ft._bone_thugs_and_harmony).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Smino - Blkswn', 'Smino', 'Blkswn', '18. Amphetamine.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Smino - Blkswn', 'Smino', 'Blkswn', '12. Blkoscars (Ft. Jay2).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'SiR - November', 'SiR', 'November', '04. DEvils.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Rich The Kid - The World Is Yours', 'Rich The Kid', 'The World Is Yours', '04. Plug Walk.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Rico Nasty & Kenny Beats - Anger Management', 'Rico Nasty & Kenny Beats', 'Anger Management', '03. Hatin.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Pusha_T-My_Name_Is_My_Name-2013-WHOA', 'unknown', 'unknown', '02-pusha_t-numbers_on_the_board-whoa.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Pro_Era-Joey_BADA-1999', 'unknown', 'unknown', '11-Joey_Bada-Snakes_Feat_T_nah_Apex_Prod_By_J_Dilla.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'pro era - PEEP The aPROcalypse final', 'pro era', 'PEEP The aPROcalypse final', '01 Like Water  - Capital STEEZ, Joey Bada$$ & Cj Fly (Produced by Statik Selektah).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'outkast - Southernplayalisticadillacmuzik (1994)', 'outkast', 'Southernplayalisticadillacmuzik (1994)', 'Southernplayalisticadillacmuzik - 02 - Myintrotoletuknow.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'maxo kream - Brandon Banks', 'maxo kream', 'Brandon Banks', '05 8 Figures.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Madvillain - Madvillainy [V0]', 'Madvillain', 'Madvillainy [V0]', '21 - Madvillain - Great Day.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'KOD', 'unknown', 'unknown', '05. J. Cole - ATM.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - Untitled Mastered', 'Kendrick Lamar', 'Untitled Mastered', '02. Untitled 02 (06.23.2014).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - Untitled Mastered', 'Kendrick Lamar', 'Untitled Mastered', '05. Untitled 05 (09.21.2014).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - Untitled Mastered', 'Kendrick Lamar', 'Untitled Mastered', '07. Untitled 07 (2014 - 2016).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - Untitled Mastered', 'Kendrick Lamar', 'Untitled Mastered', '08. Untitled 08 (09.06.2014).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - DAMN', 'Kendrick Lamar', 'DAMN', '05. FEEL..mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - DAMN', 'Kendrick Lamar', 'DAMN', '12. FEAR..mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kendrick Lamar - Bad Kid Chill City (EP) (2018) (320kbps)', 'Kendrick Lamar', 'Bad Kid Chill City (EP) (2018) (320kbps)', '06. Kendrick Lamar - Heroin (Feat. SZA, Jay Rock, Isaiah Rashad & Ab-Soul).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kanye West - Ye', 'Kanye West', 'Ye', '07. Violent Crimes feat. DeJ Loaf, Nicki Minaj & Willow Smith.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kanye West - Yandhi (2018) [mp3 V0]', 'Kanye West', 'Yandhi (2018) [mp3 V0]', '10. Denzel Interlude.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'J.I.D - The Never Story', 'J.I.D', 'The Never Story', '07. All Bad (Ft. Mereba).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'J.I.D - DiCaprio 2', 'J.I.D', 'DiCaprio 2', '06. Off Da Zoinkys.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'G.O.O.D. Music - Cruel Summer V0-2012', 'G.O.O.D. Music', 'Cruel Summer V0-2012', '04 New God Flow.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EarthGang - Rags EP', 'EarthGang', 'Rags EP', '01. Mediate.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EarthGang - Rags EP', 'EarthGang', 'Rags EP', '03. Red Light.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Future - Future', 'Future', 'Future', '17. Feds Did a Sweep.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'New folder', 'unknown', 'unknown', 'THat Part (Black Hippy REMIX).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Kanye West, Gucci Mane, Big Sean, 2 Chainz, Travis_Champions [Explicit]', 'unknown', 'unknown', '01 - Champions [Explicit].mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '01. Cocktail.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '02. Skit 1.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '03. Build.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '04. Nothing but the Best feat. Ari Lennox.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '05. Skit 2.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '06. Off the Lot feat. Mereba.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '07. LOLSMH.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'EARTHGANG - Royalty', 'EARTHGANG', 'Royalty', '08. Skit 3.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Earthgang - Robots (2017)', 'Earthgang', 'Robots (2017)', '01 - Lyfted Intro.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Earthgang - Robots (2017)', 'Earthgang', 'Robots (2017)', '02 - Artificial.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Earthgang - Robots (2017)', 'Earthgang', 'Robots (2017)', '03 - Robots.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Earthgang - Robots (2017)', 'Earthgang', 'Robots (2017)', '04 - Underwater (feat. Sir).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Earthgang - Robots (2017)', 'Earthgang', 'Robots (2017)', '05 - So Many Feelings.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Earthgang - Robots (2017)', 'Earthgang', 'Robots (2017)', '06 - Flickted.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'New folder', 'unknown', 'unknown', 'Glorious Thugs.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'ASAP Ferg - Floor Seats', 'ASAP Ferg', 'Floor Seats', 'A$AP Ferg - Floor Seats.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'ASAP Ferg - Floor Seats', 'ASAP Ferg', 'Floor Seats', 'A$AP Ferg - Jet Lag.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'ASAP Ferg - Floor Seats', 'ASAP Ferg', 'Floor Seats', 'A$AP Ferg - WAM.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'ASAP Ferg - Floor Seats', 'ASAP Ferg', 'Floor Seats', 'A$AP Ferg - Ride.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Domo Genesis - Genesis', 'Domo Genesis', 'Genesis', '07. Coming Back (Ft. Mac Miller).mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Maxo Kream - Punken', 'Maxo Kream', 'Punken', '08. Astrodome, Pt. 2.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Maxo Kream - Punken', 'Maxo Kream', 'Punken', '10. Pop Another.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Maxo Kream - Punken', 'Maxo Kream', 'Punken', '05. Hobbies.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'Little Simz - GREY Area (2019)', 'Little Simz', 'GREY Area (2019)', '08. Therapy.mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'New folder', 'unknown', 'unknown', 'Ab-Soul - W.W.S.D..mp3' )
INSERT INTO Tracks ( folder, artist, album, title ) VALUES ( 'New folder', 'unknown', 'unknown', 'Jay Electronica - better in tune w the infinite ft. LaTonya Givens.mp3' )
