# Generated by Django 3.1.3 on 2020-11-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='filename',
            field=models.FileField(default=1, upload_to='playlists/uploaded/'),
            preserve_default=False,
        ),
    ]
