# Generated by Django 3.1.3 on 2020-11-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_auto_20201113_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
